# Generated by Django 4.2.11 on 2025-02-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
    ]
